### ISSUE TITLE
Relax version requirements in examples directory?

### ISSUE THREAD

**Issue by tiran** [PyO3/setuptools-rust#124]
Would it be feasible to relax the version requirements in the examples directory? This would make it easier to use examples for unit testing in downstream packages. For example the tomlgen example requires ``pyo3 0.12.1`` but the current version is ``pyo3 0.13.2``.

https://github.com/PyO3/setuptools-rust/blob/fd4d83ea8598e64056b6c97c0e7fdb29478173c4/examples/tomlgen/setup.cfg#L12-L13

Fedora has the latest version of pyo3, which means I cannot run the example with ``rust-pyo3+default-devel``. Right now I'm [patching](https://src.fedoraproject.org/rpms/python-setuptools-rust/blob/rawhide/f/python-setuptools-rust.spec#_80) ``setup.cfg`` for testing, ``sed -i 's/"0\.[0-9.]*"/"^0"/g' setup.cfg``.

**Comment by davidhewitt** [comment]
This is an interesting question. I have a few questions:
 - Would it solve your problem if we kept this example up to date? 
   Presumably not always, because when a new `pyo3` releases we'd also need to release a new `setuptools-rust`.
 - Have you tried using a [cargo path override](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#paths-overrides)?
 
 Even with a Cargo path override, I'm not sure that the testing setup you're asking for is always guaranteed to work: what happens if we release a breaking API change to pyo3 which means this example wouldn't compile?

**Comment by davidhewitt** [comment]
@tiran FYI I just updated the examples to the latest pyo3 version, which should help your issue with the next release. (#130)
