### ISSUE TITLE
Cache the Rust build

### ISSUE THREAD

**Issue by Bendabir** [PyO3/setuptools-rust#152]
Hello,
I was wondering if there was any solution to cache the build of the Rust bindings. I sometimes need to build my Python package several times to test stuff I cannot really test with automated tests and it takes a lot of time. I couldn't find a way to cache the Rust build as my bindings are not changing very often. Any idea ?

Thanks for your help !
Ben

**Comment by davidhewitt** [comment]
Hi @Bendabir, `cargo` (which `setuptools-rust` delegates work to) has pretty good caching built in for you. In addition, it's possible to configure cargo to use additional caches such as `sccache`. I think it's out of scope of `setuptools-rust` to configure this kind of stuff.

If the problem is that you are frequently experiencing unneeded rebuilds, perhaps https://github.com/PyO3/pyo3/issues/1708 is what you are also experiencing?

**Comment by Bendabir** [comment]
Hi,
thanks for the reply ! I know that cargo has a caching mecanism and I usually don't have any issue with it when running the tests of my app. It seems to only occur at build time. I'm using PyO3 0.12.3 so I'm sure it could be related to the issue you mentionned. I might doing something wrong somewhere, I'll investiguate further !

**Comment by Bendabir** [comment]
Ok, it seems to be related to pip that is caching the wheel build when using pip install. Thanks again.

**Comment by davidhewitt** [comment]
Thanks. Is there any advice on that point you think I should add to the `setuptools-rust` docs to help future users?

**Comment by Bendabir** [comment]
I've noticed that running the build before running pip for installation fixed the issue. For example :

```bash
python setup.py bdist_wheel
pip install .
```

If I only run `pip install .`, it rebuilds the Rust bindings every time.

For information, I'm using :
- pip 21.1.2 (but I've noticed this issue since earlier versions of pip, probably 20.x)
- rust 1.48.0
- pyo3 0.12.3
