### ISSUE TITLE
Difference in use cases between setuptools-rust and pyo3-pack

### ISSUE THREAD

**Issue by rth** [PyO3/setuptools-rust#48]
The first line of the readme currently states,

> You might want to check out pyo3-pack, the successor to this project, which allows to develop, build and upload without any configuration

However, if I have a python package with a few rust extensions, one cannot use pyo3-pack to build wheels for it (that would also include the python code and possibly some C Python extensions), right? So in that use case, `setuptools-rust` will always be needed unless I am missing something?

Maybe that could be more clearly stated both in the pyo3-pack and setuptools-rust readme? I started by using `pyo3-pack` as it was advertised as "better" before realizing that `setuptools-rust` is more appropriate for my use-case.

**Comment by althonos** [comment]
Indeed, I've been using `setuptools-rust` for a project with several (optional) Rust extensions, whereas `pyo3-pack` can only a single Rust-only module for Python.

**Comment by konstin** [comment]
I'm definitely open to changing the readme to make it more clear what pyo3-pack can and can't do. I think the most basic description of what it does is "build a rust crate into a wheel". (I'd also like to support also having python code in the wheel, but that's nothing I could advertise as of now). I'd still like to point to pyo3-pack in the readme since it's more beginner friendly and not setuptools based, but it should be a more humble statement.

Regarding the multiple python extensions: Is there a special reason why you need multiple extensions and don't just bundle everything in a single cdylib?

**Comment by althonos** [comment]
Other usecase: you want provide a source release to PyPI if you cannot provide wheels for all the required platforms, end-users will still be able to use `pip install` to build you library until `pyo3` [supports PEP517](https://github.com/PyO3/pyo3-pack/issues/2).

**Comment by rth** [comment]
Closing as resolved.
